apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: madanreddy9550/spring-petclinic-discovery-server:latest
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
