apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: madanreddy9550/spring-petclinic-genai-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  type: ClusterIP
  selector:
    app: genai-service
  ports:
    - port: 8080
      targetPort: 8080
